---
# Install Gitlab and its dependencies
- name:  Install and configure dependencies
  apt:  
    name={{item}}
    state=latest
    update_cache=yes
  loop: 
    - openssh-server
    - ca-certificates
    - perl

- name: Download Gitlab repository installation script
  get_url:
    url: "{{ repository_installation_script_url }}"
    dest: /tmp/gitlab_installation_repository.sh

- name: Install Gitlab repository
  command: bash /tmp/gitlab_installation_repository.sh
  register: output

- name: Install Gitlab
  apt: 
    name: gitlab-ce
    state: present

# Reconfigure gitlab with the external_url
- name: Copy Gitlab configuration file
  lineinfile:
    path: /etc/gitlab/gitlab.rc
    regexp: '^external_url [a-z':\/.]*'
    line: external_url '"{{ external_url }}"'
  notify: restart gitlab


  