---
# This playbook deploys the whole application stack in this site

- hosts: all
  roles:
    - role: gitlab
      tags:
        - gitlab
    - role: gitlab-runner
      tags:
        - gitlab-runner
        - never
